# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "say_goodbye": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb",
         "dotp": "10_matrix_multipy.ipynb",
         "mmult": "10_matrix_multipy.ipynb"}

modules = ["core.py",
           "mmult.py"]

doc_url = "https://fastai.github.io/nbdev_template/"

git_url = "https://github.com/fastai/nbdev_template/tree/master/"

def custom_doc_links(name): return None
