# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'say_goodbye', 'HelloSayer']

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# Cell
def say_goodbye(to):
    "Say goodbye to somebody"
    return f'Goodbye {to}!'

# Cell
class HelloSayer:
    "Say hello to `to` using ['say_hello`](/nbdev_tut#say_hello)"
    def __init__(self, to): self.to = to
    def say(self): say_hello(self.to)